server {
    listen 80;
    server_name procluster.online www.procluster.online;

    root /root/test-v2/landing/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
